import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { signOutAction } from "@/components/ui/server-actions";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar session={session} signOutAction={signOutAction} />
        {children}
      </body>
    </html>
  );
}
